openapi: 3.0.3
info:
  title: Модератор API
  version: 1.0.0
  description: API для проверки релевантности текста определенной категории.

servers:
  - url: https://api.freelance.ink/moderator

paths:
  /validate:
    post:
      summary: Проверка релевантности текста категории
      description: Проверяет, соответствует ли данный текст указанной категории. Если -1, то вообще не соответсвует. Если 0, то не соответсвует частично (не критично). Если 1, то все хорошо.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
            example:
              title: "Логотип, фирменный стиль, упаковка, нейминг"
              price: 12000
              description: "Разрабатываю логотипы, нейминг, фирменный стиль, брендбук, упаковку, сайты.Посмотреть прайс можно на моём сайте: https://merkulovadesign.ru/tarifi"
      responses:
        '200':
          description: Успешный ответ с информацией о релевантности текста.
          content:
            application/json:
              schema:
                type: object
                properties:
                  relevant:
                    type: integer
                    description: Указывает, релевантен ли текст указанной теме.
                    example: 0
                  cause:
                    type: string
                example:
                  relevant: 0
                  cause: "В описании есть ссылка на другой сайт."
        '400':
          description: Ошибка запроса из-за неверного тела запроса.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "не удалось прочитать тело запроса"
        '500':
          description: Ошибка сервера при обработке запроса. Например, модель вернула текст, который сервер не смог оценить (понять).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  relevant:
                    type: string
                example:
                  message: "произошла ошибка при принятии решения"
                  result: "0"
components:
  schemas:
    ValidateRequest:
      type: object
      properties:
        title:
          type: string
          description: Заголовок услуги.
        price:
          type: string
          description: Стоимость услуги.
        description:
          type: string
          description: Текст, который нужно проверить.
