openapi: 3.0.3
info:
  title: Moderator API
  version: 1.0.0
  description: API for checking the relevance of text to a specific category.

servers:
  - url: https://api.freelance.ink/moderator

paths:
  /validate:
    post:
      summary: Check text relevance to category
      description: Verifies whether the given text fits the specified category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidateRequest'
            example:
              topic: "graphic design"
              text: "I will create a beautiful design project for your website, application, or anything else! I can help with SEO,"
      responses:
        '200':
          description: Successful response with information on text relevance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  relevant:
                    type: boolean
                    description: Indicates whether the text is relevant to the topic.
                  cause:
                    type: string
                example:
                  relevant: true
        '400':
          description: Bad request error due to invalid body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: "cannot read body"
        '500':
          description: Server error during request processing. For example, the model returned text that the server could not evaluate (understand).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  relevant:
                    type: string
                example:
                  message: "something went wrong while deciding"
                  result: "0"
components:
  schemas:
    ValidateRequest:
      type: object
      properties:
        topic:
          type: string
          description: The category for relevance checking.
        text:
          type: string
          description: The text that needs to be validated.
